# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-09 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_direction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_road',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
