# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-08 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20191208_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='enterprise_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_status_code', to='web_app.Status'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='enterprise_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_type_code', to='web_app.Status'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_status_code', to='web_app.Status'),
        ),
    ]
