# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-09 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20191209_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='expiration_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='permission',
            name='permission_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Status'),
        ),
        migrations.AddField(
            model_name='permission',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='direction',
            name='direction_road',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Road'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='enterprise_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_status_code', to='web_app.Status'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='enterprise_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_type_code', to='web_app.Status'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.User'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='permission_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.User'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='permission_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Vehicle'),
        ),
        migrations.AlterField(
            model_name='road',
            name='road_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Area'),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Station'),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.User'),
        ),
        migrations.AlterField(
            model_name='routestation',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Route'),
        ),
        migrations.AlterField(
            model_name='routestation',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Station'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Status'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_belong_code', to='web_app.Status'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_status_code', to='web_app.Status'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_type_code', to='web_app.Status'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.User'),
        ),
    ]
