# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-09 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20191209_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sta_date', models.DateTimeField(blank=True, null=True)),
                ('permission_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('sta_enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Enterprise')),
            ],
        ),
    ]
