# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-13 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_temp',
            field=models.BooleanField(default=True),
        ),
    ]
