# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-14 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_auto_20191213_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='is_temp',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),

    ]
