# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-18 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_auto_20191214_1244'),
    ]

    operations = [

    ]
