# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-18 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_auto_20191218_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_time', models.DateTimeField(blank=True, null=True)),
                ('mark_position', models.CharField(blank=True, max_length=200, null=True)),
                ('mark_content', models.CharField(blank=True, max_length=200, null=True)),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Department')),
                ('mark_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Status')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Vehicle')),
            ],
        ),
    ]
