# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-19 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='mark_cnt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
