# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-19 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_vehicle_mark_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='permission_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
