# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-20 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0011_auto_20191220_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.ForeignKey(blank=True, default=71, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Status'),
        ),
    ]
