# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-22 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0012_auto_20191220_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='unlock_content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='unlock_file',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
