# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-12-27 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20191208_1800'),
        ('web_app', '0013_auto_20191222_2316'),
    ]

    operations = [
    ]
