# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-01-01 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0016_auto_20191228_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='permission_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.Route'),
        ),
    ]
