# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-01-01 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0017_auto_20200101_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='station_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
