# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-01-28 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0021_auto_20200118_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
