# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-02 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0022_user_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='promise',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
