# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-02-05 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0023_enterprise_promise'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.User'),
        ),
    ]
