# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-08 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0025_permissionthismonth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authority',
        ),
    ]
