# Generated by Django 3.0.5 on 2020-04-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DwdTfcRltnWideInterRid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inter_id', models.CharField(blank=True, max_length=50, null=True)),
                ('inter_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_corner', models.IntegerField(blank=True, default=0, null=True)),
                ('is_signlight', models.IntegerField(blank=True, default=0, null=True)),
                ('rid', models.CharField(blank=True, max_length=50, null=True)),
                ('ft_type_no', models.IntegerField(blank=True, default=0, null=True)),
                ('rid_len', models.FloatField(blank=True, default=0, null=True)),
                ('rid_lnglat_seq', models.CharField(blank=True, max_length=500, null=True)),
                ('rid_name', models.CharField(blank=True, max_length=50, null=True)),
                ('rid_angle', models.FloatField(blank=True, default=0, null=True)),
                ('rid_dir_4_no', models.IntegerField(blank=True, default=0, null=True)),
                ('rid_dir_8_no', models.IntegerField(blank=True, default=0, null=True)),
                ('rid_road_level', models.IntegerField(blank=True, default=0, null=True)),
                ('rid_type_no', models.IntegerField(blank=True, default=0, null=True)),
                ('rid_pass_type_no', models.IntegerField(blank=True, default=0, null=True)),
                ('rid_overlap', models.IntegerField(blank=True, default=0, null=True)),
                ('rid_median', models.IntegerField(blank=True, default=0, null=True)),
                ('rid_walkway', models.IntegerField(blank=True, default=0, null=True)),
                ('ft_angle', models.FloatField(blank=True, default=0, null=True)),
                ('ft_dir_4_no', models.IntegerField(blank=True, default=0, null=True)),
                ('ft_dir_8_no', models.IntegerField(blank=True, default=0, null=True)),
                ('dt', models.CharField(blank=True, max_length=20, null=True)),
                ('adcode', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OdsSignalFroadInfoScats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_signal_id', models.CharField(blank=True, max_length=20, null=True)),
                ('cust_froad_id', models.CharField(blank=True, max_length=10, null=True)),
                ('cust_froad_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cust_froad_lane_num', models.IntegerField(blank=True, default=0, null=True)),
                ('cust_froad_angle', models.IntegerField(blank=True, default=None, null=True)),
                ('cust_troad_lane_num', models.IntegerField(blank=True, default=0, null=True)),
                ('staff_street_type', models.CharField(blank=True, max_length=10, null=True)),
                ('center_div_type', models.CharField(blank=True, max_length=10, null=True)),
                ('lane_func_def', models.CharField(blank=True, max_length=50, null=True)),
                ('up_cust_signal_id', models.CharField(blank=True, max_length=20, null=True)),
                ('dt', models.CharField(blank=True, max_length=20, null=True)),
                ('adcode', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
