# Generated by Django 3.0.5 on 2020-04-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rid_map', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OdsSignalFroadInfoScats',
            new_name='CustFroad',
        ),
        migrations.RenameModel(
            old_name='DwdTfcRltnWideInterRid',
            new_name='InterRid',
        ),
    ]
