# Generated by Django 3.0.5 on 2020-04-27 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rid_map', '0002_auto_20200427_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interrid',
            old_name='dt',
            new_name='data_version',
        ),
    ]
