# Generated by Django 3.0.5 on 2020-05-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rid_map', '0004_auto_20200506_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustSignalInterMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_signal_id', models.CharField(blank=True, max_length=20, null=True)),
                ('inter_id', models.CharField(blank=True, max_length=50, null=True)),
                ('area_code', models.CharField(blank=True, max_length=20, null=True)),
                ('data_version', models.CharField(blank=True, max_length=20, null=True)),
                ('adcode', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
