# Generated by Django 3.0.5 on 2020-05-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rid_map', '0005_custsignalintermap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custsignalintermap',
            old_name='adcode',
            new_name='cust_inter_id',
        ),
        migrations.RenameField(
            model_name='custsignalintermap',
            old_name='cust_signal_id',
            new_name='gmt_invalid',
        ),
        migrations.RemoveField(
            model_name='custsignalintermap',
            name='data_version',
        ),
        migrations.AddField(
            model_name='custsignalintermap',
            name='cust_inter_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='custsignalintermap',
            name='inter_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='custsignalintermap',
            name='is_valid',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='custsignalintermap',
            name='inter_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
