# Generated by Django 3.0.5 on 2020-05-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rid_map', '0006_auto_20200507_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='custsignalintermap',
            name='grid_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
