# Generated by Django 3.0.5 on 2020-05-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rid_map', '0007_custsignalintermap_grid_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadridmap',
            name='inter',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
