# Generated by Django 3.0.5 on 2020-05-07 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rid_map', '0008_roadridmap_inter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roadridmap',
            old_name='inter',
            new_name='inter_id',
        ),
    ]
