# Generated by Django 3.0.5 on 2020-05-08 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rid_map', '0010_auto_20200507_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterOutRid',
            fields=[
                ('inter_id', models.CharField(blank=True, max_length=50, null=True)),
                ('inter_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_corner', models.IntegerField(blank=True, default=0, null=True)),
                ('is_signlight', models.IntegerField(blank=True, default=0, null=True)),
                ('rid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ft_type_no', models.IntegerField(blank=True, default=0, null=True)),
                ('rid_len', models.FloatField(blank=True, default=0, null=True)),
                ('rid_lnglat_seq', models.CharField(blank=True, max_length=500, null=True)),
                ('rid_name', models.CharField(blank=True, max_length=50, null=True)),
                ('rid_angle', models.FloatField(blank=True, default=0, null=True)),
                ('rid_dir_4_no', models.IntegerField(blank=True, default=0, null=True)),
                ('rid_dir_8_no', models.IntegerField(blank=True, default=0, null=True)),
                ('rid_road_level', models.IntegerField(blank=True, default=0, null=True)),
                ('rid_type_no', models.IntegerField(blank=True, default=0, null=True)),
                ('rid_pass_type_no', models.IntegerField(blank=True, default=0, null=True)),
                ('rid_overlap', models.IntegerField(blank=True, default=0, null=True)),
                ('rid_median', models.IntegerField(blank=True, default=0, null=True)),
                ('rid_walkway', models.IntegerField(blank=True, default=0, null=True)),
                ('ft_angle', models.FloatField(blank=True, default=0, null=True)),
                ('ft_dir_4_no', models.IntegerField(blank=True, default=0, null=True)),
                ('ft_dir_8_no', models.IntegerField(blank=True, default=0, null=True)),
                ('data_version', models.CharField(blank=True, max_length=20, null=True)),
                ('adcode', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadOutRidMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inter_id', models.CharField(blank=True, max_length=20, null=True)),
                ('cust_signal_id', models.CharField(blank=True, max_length=20, null=True)),
                ('cust_froad_id', models.CharField(blank=True, max_length=10, null=True)),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rid_map.InterRid')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rid_map.CustFroad')),
            ],
        ),
    ]
