# Generated by Django 3.0.5 on 2020-05-09 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rid_map', '0011_interoutrid_roadoutridmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadoutridmap',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rid_map.InterOutRid'),
        ),
    ]
