# Generated by Django 3.0.5 on 2020-05-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rid_map', '0012_auto_20200509_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightRoadRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_signal_id', models.CharField(blank=True, max_length=20, null=True)),
                ('lightset_id', models.CharField(blank=True, max_length=20, null=True)),
                ('lightset_content', models.CharField(blank=True, max_length=50, null=True)),
                ('dt', models.CharField(blank=True, max_length=20, null=True)),
                ('adcode', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhaseLightRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_signal_id', models.CharField(blank=True, max_length=20, null=True)),
                ('phase_name', models.CharField(blank=True, max_length=20, null=True)),
                ('lightset_id_list', models.CharField(blank=True, max_length=50, null=True)),
                ('dt', models.CharField(blank=True, max_length=20, null=True)),
                ('adcode', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
