# Generated by Django 3.0.5 on 2020-05-27 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rid_map', '0014_interftrid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadFTRidMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inter_id', models.CharField(blank=True, max_length=20, null=True)),
                ('f_rid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rid_map.InterRid')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rid_map.CustFroad')),
                ('t_rid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rid_map.InterOutRid')),
            ],
        ),
    ]
