# Generated by Django 3.0.5 on 2020-06-01 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rid_map', '0015_roadftridmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseFroadFTRidMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inter_id', models.CharField(blank=True, max_length=20, null=True)),
                ('phase_name', models.CharField(blank=True, max_length=10, null=True)),
                ('f_rid', models.CharField(blank=True, max_length=50, null=True)),
                ('t_rid', models.CharField(blank=True, max_length=50, null=True)),
                ('turn_dir_no', models.CharField(blank=True, max_length=10, null=True)),
                ('f_road', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='f_road', to='rid_map.CustFroad')),
                ('ft_rid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rid_map.InterFTRid')),
                ('t_road', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='t_road', to='rid_map.CustFroad')),
            ],
        ),
    ]
