# Generated by Django 3.0.5 on 2020-06-01 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rid_map', '0016_phasefroadftridmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasefroadftridmap',
            name='cust_turn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='phasefroadftridmap',
            name='f_road',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='f_road', to='rid_map.CustFroad'),
        ),
        migrations.AlterField(
            model_name='phasefroadftridmap',
            name='t_road',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='t_road', to='rid_map.CustFroad'),
        ),
    ]
