# Generated by Django 3.0.5 on 2020-06-02 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rid_map', '0018_auto_20200601_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phasefroadftridmap',
            name='f_rid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rid_map.InterRid'),
        ),
        migrations.AlterField(
            model_name='phasefroadftridmap',
            name='t_rid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rid_map.InterOutRid'),
        ),
    ]
