# Generated by Django 3.0.5 on 2020-08-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rid_map', '0019_auto_20200602_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustTimePlanJinshan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(blank=True, max_length=20, null=True)),
                ('split_plan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('cycle_time', models.CharField(blank=True, max_length=20, null=True)),
                ('barrier_num', models.CharField(blank=True, max_length=20, null=True)),
                ('barrier_list', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
