# Generated by Django 3.0.5 on 2020-08-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rid_map', '0020_custtimeplanjinshan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custtimeplanjinshan',
            name='barrier_list',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='custtimeplanjinshan',
            name='barrier_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='custtimeplanjinshan',
            name='cycle_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='custtimeplanjinshan',
            name='split_plan_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
