# Generated by Django 3.0.5 on 2020-09-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rid_map', '0021_auto_20200817_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseIdPhaseNoMapJinshan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(blank=True, max_length=20, null=True)),
                ('split_plan_no', models.CharField(blank=True, max_length=10, null=True)),
                ('phase_id', models.CharField(blank=True, max_length=20, null=True)),
                ('phase_no', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
