# Generated by Django 3.0.5 on 2020-09-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rid_map', '0022_phaseidphasenomapjinshan'),
    ]

    operations = [
        migrations.AddField(
            model_name='phaseidphasenomapjinshan',
            name='light_list',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
