# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-21 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('enterprise_name', models.CharField(blank=True, max_length=200, null=True)),
                ('enterprise_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('legal_person', models.CharField(blank=True, max_length=50, null=True)),
                ('organization_code', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tj_orta_app.Authority')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('engine', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(blank=True, max_length=50, null=True)),
                ('register_date', models.DateField(blank=True, null=True)),
                ('route', models.CharField(blank=True, max_length=400, null=True)),
                ('modify_time', models.DateTimeField(blank=True, null=True)),
                ('submit_time', models.DateTimeField(blank=True, null=True)),
                ('hbj_time', models.DateTimeField(blank=True, null=True)),
                ('jgj_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tj_orta_app.Status')),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tj_orta_app.Type')),
            ],
        ),
    ]
