# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-23 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tj_orta_app', '0004_vehicle_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
