# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-23 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tj_orta_app', '0005_vehicle_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
