# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-24 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tj_orta_app', '0007_vehicle_cert_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='engine',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
