# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-14 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tj_orta_app', '0009_auto_20180502_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_submit', models.BooleanField(default=True)),
            ],
        ),
    ]
