# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-14 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tj_orta_app', '0010_sysstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('cert_id', models.CharField(blank=True, max_length=30, null=True)),
                ('submit_time', models.DateTimeField(blank=True, null=True)),
                ('hbj_time', models.DateTimeField(blank=True, null=True)),
                ('jgj_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tj_orta_app.Status')),
            ],
        ),
    ]
