# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-19 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tj_orta_app', '0013_backup1_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
