# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-20 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tj_orta_app', '0014_auto_20190419_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('cert_id', models.CharField(blank=True, max_length=30, null=True)),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tj_orta_app.User')),
            ],
        ),
    ]
