# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-20 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tj_orta_app', '0015_vehicleman'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleman',
            name='route',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
