# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-23 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tj8890_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('person', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency', models.IntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('accept_time', models.DateTimeField(blank=True, null=True)),
                ('limit_time', models.DateTimeField(blank=True, null=True)),
                ('dead_time', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('result', models.CharField(blank=True, max_length=500, null=True)),
                ('delay_time', models.DateTimeField(blank=True, null=True)),
                ('delay_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('return_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('save_time', models.DateTimeField(blank=True, null=True)),
                ('is_exported', models.BooleanField(default=False)),
                ('accept_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accept_user', to='tj8890_user.User')),
                ('assign_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tj8890_user.Dept')),
                ('cate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tj8890_item.Cate')),
                ('reject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reject_user', to='tj8890_user.User')),
            ],
        ),
        migrations.CreateModel(
            name='ItemStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='tj8890_item.ItemStatus'),
        ),
    ]
