# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-09 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tj8890_item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='category1',
        ),
        migrations.AddField(
            model_name='item',
            name='category2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='category3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='category4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
