# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-11 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tj8890_item', '0002_auto_20180409_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('cate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tj8890_item.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='category1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category1_set', to='tj8890_item.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category2_set', to='tj8890_item.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category3_set', to='tj8890_item.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category4_set', to='tj8890_item.Category'),
        ),
    ]
