# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-24 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tj8890_item', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='approval_content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='approval_person',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
