# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-17 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tj8890_item', '0003_auto_20180411_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deliver_person',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
