# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-27 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tj8890_item', '0003_auto_20181024_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cate1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cate1', to='tj8890_item.Category'),
        ),
        migrations.AddField(
            model_name='item',
            name='cate2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cate2', to='tj8890_item.Category'),
        ),
        migrations.AddField(
            model_name='item',
            name='cate3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cate3', to='tj8890_item.Category'),
        ),
    ]
