# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-15 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tj8890_user', '0002_auto_20180405_1653'),
        ('tj8890_item', '0004_item_deliver_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
