# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-05 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tj8890_user', '0002_auto_20180405_1653'),
        ('tj8890_item', '0004_auto_20180905_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='accept_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accept_user', to='tj8890_user.User'),
        ),
        migrations.AddField(
            model_name='item',
            name='assign_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tj8890_user.Dept'),
        ),
        migrations.AddField(
            model_name='item',
            name='reject_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reject_user', to='tj8890_user.User'),
        ),
    ]
