# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-05 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tj8890_item', '0005_auto_20180905_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='receive_time',
            new_name='accept_time',
        ),
    ]
