# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-15 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tj8890_user', '0002_auto_20180405_1653'),
        ('tj8890_item', '0005_auto_20180815_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='deliver_person',
        ),
        migrations.AddField(
            model_name='item',
            name='assign_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_dept_set', to='tj8890_user.Dept'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='tj8890_item.ItemStatus'),
        ),
    ]
