# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-11 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tj8890_item', '0006_auto_20180905_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='source',
        ),
        migrations.AddField(
            model_name='item',
            name='dead_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
