# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-12 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tj8890_item', '0011_item_return_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_exported',
            field=models.BooleanField(default=False),
        ),
    ]
