# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-13 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tj8890_item', '0012_item_is_exported'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='save_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
