# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-23 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tj8890_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_name', models.CharField(blank=True, max_length=50, null=True)),
                ('info_abstract', models.CharField(blank=True, max_length=200, null=True)),
                ('info_content', models.CharField(blank=True, max_length=500, null=True)),
                ('upload_time', models.DateTimeField(blank=True, null=True)),
                ('upload_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tj8890_user.User')),
            ],
        ),
    ]
