# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-28 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tj8890_item', '0002_auto_20180827_2031'),
        ('tj8890_user', '0002_auto_20180405_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_name', models.CharField(blank=True, max_length=50, null=True)),
                ('info_abstract', models.CharField(blank=True, max_length=200, null=True)),
                ('info_content', models.CharField(blank=True, max_length=500, null=True)),
                ('upload_time', models.DateTimeField(blank=True, null=True)),
                ('cate1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cate1_set', to='tj8890_item.Category')),
                ('cate2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cate2_set', to='tj8890_item.Category')),
                ('cate3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cate3_set', to='tj8890_item.Category')),
                ('cate4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cate4_set', to='tj8890_item.Category')),
                ('upload_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tj8890_user.User')),
            ],
        ),
    ]
