# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-05 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tj8890_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='cate1',
        ),
        migrations.RemoveField(
            model_name='information',
            name='cate2',
        ),
        migrations.RemoveField(
            model_name='information',
            name='cate3',
        ),
        migrations.RemoveField(
            model_name='information',
            name='cate4',
        ),
    ]
