# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-04 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_api_tsn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VioCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('activity', models.CharField(max_length=200)),
                ('point', models.IntegerField(default=0)),
                ('fine', models.IntegerField(default=0)),
            ],
        ),
    ]
